import { createClient, SupabaseClient, User as SupabaseUser } from '@supabase/supabase-js';
import bcrypt from 'bcryptjs';
import { TeamUser, UserRole, UsuarioDbRecord, NewUsuarioPayload } from '../types';

// Environment variables configured via .env / Vite
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

// Check if credentials are appropriately supplied
export const isSupabaseConfigured = (): boolean => {
  return (
    Boolean(supabaseUrl) &&
    Boolean(supabaseAnonKey) &&
    !supabaseUrl.includes('your-project') &&
    !supabaseAnonKey.includes('your-anon-public-key')
  );
};

// Singleton Supabase client instance (or null if unconfigured)
export const supabase: SupabaseClient | null = isSupabaseConfigured()
  ? createClient(supabaseUrl, supabaseAnonKey, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      },
    })
  : null;

/**
 * Converts a Supabase Auth User object into the application's internal TeamUser model.
 */
export const mapSupabaseUserToTeamUser = (user: SupabaseUser): TeamUser => {
  const metadata = user.user_metadata || {};
  const email = user.email || 'usuario@empresa.com.br';
  const name =
    (metadata.full_name as string) ||
    (metadata.name as string) ||
    (email.includes('@') ? email.split('@')[0].replace('.', ' ') : 'Usuário DataCore');

  const role: UserRole = (metadata.role as UserRole) || 'admin';
  const department = (metadata.department as string) || 'Engenharia de Dados & Governança';
  const initials =
    name
      .split(' ')
      .slice(0, 2)
      .map((n: string) => n[0]?.toUpperCase() || '')
      .join('') || email.substring(0, 2).toUpperCase();

  return {
    id: user.id,
    name,
    email,
    role,
    department,
    avatar: initials,
    lastActive: 'Agora',
    mfaEnabled: Boolean(metadata.mfa_enabled),
    canViewUnmaskedPII: role === 'admin' || role === 'dpo_compliance',
  };
};

/**
 * Computes SHA-256 hex string from plain text
 */
export async function computeSha256(text: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(text);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Computes SHA-512 hex string from plain text
 */
export async function computeSha512(text: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(text);
  const hashBuffer = await crypto.subtle.digest('SHA-512', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Generates a standard Bcrypt hash (salt round 10) for storing in public.usuarios
 */
export function generateBcryptHash(plainText: string): string {
  const salt = bcrypt.genSaltSync(10);
  return bcrypt.hashSync(plainText, salt);
}

/**
 * Verifies a plain password against the stored senha_hash in the database.
 * Supports:
 * 1. Direct match (plain text)
 * 2. Bcrypt hash ($2a$, $2b$, $2y$ generated by crypt/gen_salt or bcrypt)
 * 3. SHA-256 hex hash (64 chars)
 * 4. SHA-512 hex hash (128 chars)
 */
export async function verifyPasswordHash(plainPassword: string, storedHash: string): Promise<boolean> {
  if (!storedHash || !plainPassword) return false;

  const trimmedHash = storedHash.trim();

  // 1. Direct equality check (useful for tests or plain passwords)
  if (trimmedHash === plainPassword) {
    return true;
  }

  // 2. Bcrypt verification ($2a$, $2b$, $2y$, etc.)
  if (
    trimmedHash.startsWith('$2a$') ||
    trimmedHash.startsWith('$2b$') ||
    trimmedHash.startsWith('$2y$') ||
    trimmedHash.startsWith('$2$')
  ) {
    try {
      const isMatch = bcrypt.compareSync(plainPassword, trimmedHash);
      if (isMatch) return true;
    } catch {
      // Continue to next check if bcrypt throws
    }
  }

  // 3. SHA-256 comparison
  try {
    const sha256Hex = await computeSha256(plainPassword);
    if (sha256Hex.toLowerCase() === trimmedHash.toLowerCase()) {
      return true;
    }
  } catch {
    // ignore
  }

  // 4. SHA-512 comparison
  try {
    const sha512Hex = await computeSha512(plainPassword);
    if (sha512Hex.toLowerCase() === trimmedHash.toLowerCase()) {
      return true;
    }
  } catch {
    // ignore
  }

  // 5. Try bcrypt as fallback even if prefix is unusual
  try {
    if (bcrypt.compareSync(plainPassword, trimmedHash)) {
      return true;
    }
  } catch {
    // not bcrypt
  }

  return false;
}

/**
 * Maps a row from the Supabase 'usuarios' (or 'usuario') table into the DataCore TeamUser model
 */
export function mapUsuarioRowToTeamUser(row: Record<string, unknown>): TeamUser {
  const id = String(row.id || row.id_usuario || row.codigo || `usr-${Date.now()}`);
  const email = String(row.email || 'usuario@empresa.com.br');
  const name =
    (row.nome as string) ||
    (row.name as string) ||
    (row.nome_completo as string) ||
    (email.includes('@') ? email.split('@')[0].replace('.', ' ') : 'Usuário DataCore');

  // Normalize role / papel / perfil
  const rawRole = String(
    row.papel || row.role || row.perfil || row.cargo || row.tipo || ''
  ).toLowerCase();
  let role: UserRole = 'viewer';

  if (rawRole.includes('engineer') || rawRole.includes('engenheir') || rawRole.includes('dev')) {
    role = 'data_engineer';
  } else if (rawRole.includes('dpo') || rawRole.includes('compliance') || rawRole.includes('privacid')) {
    role = 'dpo_compliance';
  } else if (rawRole.includes('analyst') || rawRole.includes('analist')) {
    role = 'data_analyst';
  } else if (rawRole.includes('admin') || rawRole.includes('gestor') || rawRole.includes('coord')) {
    role = 'admin';
  } else if (rawRole.includes('viewer') || rawRole.includes('leitor') || rawRole.includes('consult')) {
    role = 'viewer';
  } else {
    role = 'viewer';
  }

  const department =
    (row.departamento as string) ||
    (row.setor as string) ||
    (row.area as string) ||
    'Engenharia de Dados & Governança';

  const avatar =
    (row.avatar_iniciais as string) ||
    name
      .split(' ')
      .slice(0, 2)
      .map((n: string) => n[0]?.toUpperCase() || '')
      .join('') || email.substring(0, 2).toUpperCase();

  const mfaEnabled = Boolean(
    row.mfa_habilitado !== undefined ? row.mfa_habilitado : (row.mfa_enabled || row.mfa)
  );

  const canViewUnmaskedPII = Boolean(
    row.pode_visualizar_pii_bruto !== undefined
      ? row.pode_visualizar_pii_bruto
      : (role === 'admin' || role === 'dpo_compliance')
  );

  return {
    id,
    name,
    email,
    role,
    department,
    avatar,
    lastActive: row.ultimo_acesso_em ? new Date(String(row.ultimo_acesso_em)).toLocaleDateString('pt-BR') : 'Agora',
    mfaEnabled,
    canViewUnmaskedPII,
  };
}

/**
 * Authenticates directly against the 'usuarios' (or 'usuario') table in Supabase
 * Validating email and senha_hash.
 */
export async function authenticateWithUsuarioTable(
  emailInput: string,
  passwordInput: string
): Promise<{ user: TeamUser; role: UserRole }> {
  if (!supabase) {
    throw new Error(
      'O cliente Supabase não está configurado. Configure as variáveis VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY no arquivo .env.'
    );
  }

  const cleanEmail = emailInput.trim().toLowerCase();

  // Try querying 'usuarios' first (the new schema), fallback to 'usuario'
  let data: Record<string, unknown>[] | null = null;
  let queryError: unknown = null;

  const resUsuarios = await supabase
    .from('usuarios')
    .select('*')
    .ilike('email', cleanEmail)
    .limit(1);

  if (!resUsuarios.error && resUsuarios.data) {
    data = resUsuarios.data as Record<string, unknown>[];
  } else {
    // Try fallback to 'usuario' if 'usuarios' returned an error (e.g. table not found 42P01)
    const resUsuario = await supabase
      .from('usuario')
      .select('*')
      .ilike('email', cleanEmail)
      .limit(1);

    if (!resUsuario.error && resUsuario.data) {
      data = resUsuario.data as Record<string, unknown>[];
    } else {
      queryError = resUsuarios.error || resUsuario.error;
    }
  }

  if (queryError && (!data || data.length === 0)) {
    console.error('Erro ao consultar tabela de usuários no Supabase:', queryError);
    const errObj = queryError as { code?: string; message?: string };
    
    if (errObj.code === '42P01') {
      throw new Error(
        'A tabela "usuarios" (ou "usuario") não foi encontrada no banco Supabase. Certifique-se de criá-la no schema public.'
      );
    }
    
    if (errObj.message?.includes('row-level security') || errObj.code === '42501') {
      throw new Error(
        'Acesso bloqueado por RLS na tabela "usuarios". Habilite política de SELECT para a role anon.'
      );
    }

    throw new Error(`Erro ao consultar tabela de usuários: ${errObj.message || 'Falha de conexão'}`);
  }

  if (!data || data.length === 0) {
    throw new Error('Nenhum usuário encontrado com este e-mail na tabela "usuarios".');
  }

  const usuarioRow = data[0];

  // Check account status if column exists (ind_cadastro_ativo, ativo, etc.)
  if (
    usuarioRow.ind_cadastro_ativo === false ||
    usuarioRow.ativo === false ||
    usuarioRow.status === 'inativo' ||
    usuarioRow.bloqueado === true
  ) {
    throw new Error('Este usuário está inativo ou suspenso no sistema.');
  }

  // Validate senha_hash column
  const storedHash = (usuarioRow.senha_hash as string) || (usuarioRow.senha as string);

  if (!storedHash) {
    throw new Error('A coluna "senha_hash" não foi encontrada ou está vazia para este usuário.');
  }

  const isPasswordValid = await verifyPasswordHash(passwordInput, storedHash);

  if (!isPasswordValid) {
    throw new Error('Senha incorreta. Verifique suas credenciais de acesso.');
  }

  // Update ultimo_acesso_em if possible (fire & forget)
  try {
    const tableName = (usuarioRow.ind_cadastro_ativo !== undefined) ? 'usuarios' : 'usuario';
    await supabase
      .from(tableName)
      .update({ ultimo_acesso_em: new Date().toISOString() })
      .eq('id', usuarioRow.id);
  } catch {
    // Ignore update failures
  }

  const teamUser = mapUsuarioRowToTeamUser(usuarioRow);
  return { user: teamUser, role: teamUser.role };
}

/**
 * Registers a new user directly into the 'usuarios' table in Supabase
 */
export async function cadastrarUsuarioNaTabela(
  payload: NewUsuarioPayload
): Promise<TeamUser> {
  const cleanEmail = payload.email.trim().toLowerCase();
  const cleanNome = payload.nome.trim();

  // Generate initials for avatar
  const avatarIniciais =
    cleanNome
      .split(' ')
      .filter(Boolean)
      .slice(0, 2)
      .map(part => part[0]?.toUpperCase() || '')
      .join('') || cleanEmail.substring(0, 2).toUpperCase();

  // Hash the plain password using standard Bcrypt
  const senhaHash = generateBcryptHash(payload.senha);

  const newRecord: UsuarioDbRecord = {
    nome: cleanNome,
    email: cleanEmail,
    senha_hash: senhaHash,
    papel: payload.papel,
    departamento: payload.departamento.trim() || 'Engenharia de Dados & Governança',
    avatar_iniciais: avatarIniciais,
    mfa_habilitado: Boolean(payload.mfa_habilitado),
    pode_visualizar_pii_bruto: Boolean(payload.pode_visualizar_pii_bruto),
    ind_cadastro_ativo: true,
    id_empresa: payload.id_empresa || null,
  };

  if (isSupabaseConfigured() && supabase) {
    // Attempt inserting into 'usuarios'
    let insertResult = await supabase
      .from('usuarios')
      .insert([newRecord])
      .select()
      .single();

    if (insertResult.error) {
      // If table 'usuarios' doesn't exist, try fallback 'usuario'
      if (insertResult.error.code === '42P01') {
        const fallbackRecord = {
          nome: newRecord.nome,
          email: newRecord.email,
          senha_hash: newRecord.senha_hash,
          perfil: newRecord.papel,
          departamento: newRecord.departamento,
          ativo: true,
        };
        const fbResult = await supabase
          .from('usuario')
          .insert([fallbackRecord])
          .select()
          .single();

        if (fbResult.error) {
          throw new Error(`Erro ao cadastrar na tabela de usuários: ${fbResult.error.message}`);
        }
        insertResult = fbResult;
      } else if (insertResult.error.code === '23505') {
        throw new Error(`Já existe um usuário cadastrado com o e-mail "${cleanEmail}".`);
      } else {
        throw new Error(`Erro ao salvar usuário no Supabase: ${insertResult.error.message}`);
      }
    }

    return mapUsuarioRowToTeamUser(insertResult.data as Record<string, unknown>);
  } else {
    // Local demo simulation
    const localUser: TeamUser = {
      id: `usr-${Date.now()}`,
      name: cleanNome,
      email: cleanEmail,
      role: payload.papel,
      department: payload.departamento || 'Engenharia de Dados & Governança',
      avatar: avatarIniciais,
      lastActive: 'Agora',
      mfaEnabled: Boolean(payload.mfa_habilitado),
      canViewUnmaskedPII: Boolean(payload.pode_visualizar_pii_bruto),
    };
    return localUser;
  }
}

/**
 * Log out from Supabase and clear session
 */
export async function logoutFromSupabase(): Promise<void> {
  if (supabase) {
    try {
      await supabase.auth.signOut();
    } catch {
      // ignore
    }
  }
}
