import { createClient, SupabaseClient, User as SupabaseUser } from '@supabase/supabase-js';
import bcrypt from 'bcryptjs';
import {
  TeamUser, UserRole, UsuarioDbRecord, NewUsuarioPayload, Empresa,
  SourceConnectorConfig, DestinationConnectorConfig, AutoIntegration,
  SourceType, DestinationType, CloudProvider, TableSyncConfig, SyncFrequencyOption
} from '../types';

// Environment variables configured via .env / Vite
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

// Check if credentials are appropriately supplied
export const isSupabaseConfigured = (): boolean => {
  return (
    Boolean(supabaseUrl) &&
    Boolean(supabaseAnonKey) &&
    !supabaseUrl.includes('your-project') &&
    !supabaseAnonKey.includes('your-anon-public-key')
  );
};

// Singleton Supabase client instance (or null if unconfigured)
export const supabase: SupabaseClient | null = isSupabaseConfigured()
  ? createClient(supabaseUrl, supabaseAnonKey, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      },
    })
  : null;

/**
 * Converts a Supabase Auth User object into the application's internal TeamUser model.
 */
export const mapSupabaseUserToTeamUser = (user: SupabaseUser): TeamUser => {
  const metadata = user.user_metadata || {};
  const email = user.email || 'usuario@empresa.com.br';
  const name =
    (metadata.full_name as string) ||
    (metadata.name as string) ||
    (email.includes('@') ? email.split('@')[0].replace('.', ' ') : 'Usuário DataCore');

  const role: UserRole = (metadata.role as UserRole) || 'admin';
  const department = (metadata.department as string) || 'Engenharia de Dados & Governança';
  const initials =
    name
      .split(' ')
      .slice(0, 2)
      .map((n: string) => n[0]?.toUpperCase() || '')
      .join('') || email.substring(0, 2).toUpperCase();

  return {
    id: user.id,
    name,
    email,
    role,
    department,
    avatar: initials,
    lastActive: 'Agora',
    mfaEnabled: Boolean(metadata.mfa_enabled),
    canViewUnmaskedPII: role === 'admin' || role === 'dpo_compliance',
  };
};

/**
 * Computes SHA-256 hex string from plain text
 */
export async function computeSha256(text: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(text);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Computes SHA-512 hex string from plain text
 */
export async function computeSha512(text: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(text);
  const hashBuffer = await crypto.subtle.digest('SHA-512', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Generates a standard Bcrypt hash (salt round 10) for storing in public.usuarios
 */
export function generateBcryptHash(plainText: string): string {
  const salt = bcrypt.genSaltSync(10);
  return bcrypt.hashSync(plainText, salt);
}

/**
 * Verifies a plain password against the stored senha_hash in the database.
 * Supports:
 * 1. Direct match (plain text)
 * 2. Bcrypt hash ($2a$, $2b$, $2y$ generated by crypt/gen_salt or bcrypt)
 * 3. SHA-256 hex hash (64 chars)
 * 4. SHA-512 hex hash (128 chars)
 */
export async function verifyPasswordHash(plainPassword: string, storedHash: string): Promise<boolean> {
  if (!storedHash || !plainPassword) return false;

  const trimmedHash = storedHash.trim();

  // 1. Direct equality check (useful for tests or plain passwords)
  if (trimmedHash === plainPassword) {
    return true;
  }

  // 2. Bcrypt verification ($2a$, $2b$, $2y$, etc.)
  if (
    trimmedHash.startsWith('$2a$') ||
    trimmedHash.startsWith('$2b$') ||
    trimmedHash.startsWith('$2y$') ||
    trimmedHash.startsWith('$2$')
  ) {
    try {
      const isMatch = bcrypt.compareSync(plainPassword, trimmedHash);
      if (isMatch) return true;
    } catch {
      // Continue to next check if bcrypt throws
    }
  }

  // 3. SHA-256 comparison
  try {
    const sha256Hex = await computeSha256(plainPassword);
    if (sha256Hex.toLowerCase() === trimmedHash.toLowerCase()) {
      return true;
    }
  } catch {
    // ignore
  }

  // 4. SHA-512 comparison
  try {
    const sha512Hex = await computeSha512(plainPassword);
    if (sha512Hex.toLowerCase() === trimmedHash.toLowerCase()) {
      return true;
    }
  } catch {
    // ignore
  }

  // 5. Try bcrypt as fallback even if prefix is unusual
  try {
    if (bcrypt.compareSync(plainPassword, trimmedHash)) {
      return true;
    }
  } catch {
    // not bcrypt
  }

  return false;
}

/**
 * Maps a row from the Supabase 'usuarios' (or 'usuario') table into the DataCore TeamUser model
 */
export function mapUsuarioRowToTeamUser(row: Record<string, unknown>): TeamUser {
  const id = String(row.id || row.id_usuario || row.codigo || `usr-${Date.now()}`);
  const email = String(row.email || 'usuario@empresa.com.br');
  const name =
    (row.nome as string) ||
    (row.name as string) ||
    (row.nome_completo as string) ||
    (email.includes('@') ? email.split('@')[0].replace('.', ' ') : 'Usuário DataCore');

  // Normalize role / papel / perfil
  const rawRole = String(
    row.papel || row.role || row.perfil || row.cargo || row.tipo || ''
  ).toLowerCase();
  let role: UserRole = 'viewer';

  if (rawRole.includes('engineer') || rawRole.includes('engenheir') || rawRole.includes('dev')) {
    role = 'data_engineer';
  } else if (rawRole.includes('dpo') || rawRole.includes('compliance') || rawRole.includes('privacid')) {
    role = 'dpo_compliance';
  } else if (rawRole.includes('analyst') || rawRole.includes('analist')) {
    role = 'data_analyst';
  } else if (rawRole.includes('admin') || rawRole.includes('gestor') || rawRole.includes('coord')) {
    role = 'admin';
  } else if (rawRole.includes('viewer') || rawRole.includes('leitor') || rawRole.includes('consult')) {
    role = 'viewer';
  } else {
    role = 'viewer';
  }

  const department =
    (row.departamento as string) ||
    (row.setor as string) ||
    (row.area as string) ||
    'Engenharia de Dados & Governança';

  const avatar =
    (row.avatar_iniciais as string) ||
    name
      .split(' ')
      .slice(0, 2)
      .map((n: string) => n[0]?.toUpperCase() || '')
      .join('') || email.substring(0, 2).toUpperCase();

  const mfaEnabled = Boolean(
    row.mfa_habilitado !== undefined ? row.mfa_habilitado : (row.mfa_enabled || row.mfa)
  );

  const canViewUnmaskedPII = Boolean(
    row.pode_visualizar_pii_bruto !== undefined
      ? row.pode_visualizar_pii_bruto
      : (role === 'admin' || role === 'dpo_compliance')
  );

  const idEmpresa = row.id_empresa !== undefined && row.id_empresa !== null
    ? Number(row.id_empresa)
    : null;

  return {
    id,
    name,
    email,
    role,
    department,
    avatar,
    lastActive: row.ultimo_acesso_em ? new Date(String(row.ultimo_acesso_em)).toLocaleDateString('pt-BR') : 'Agora',
    mfaEnabled,
    canViewUnmaskedPII,
    idEmpresa,
  };
}

/**
 * Authenticates directly against the 'usuarios' (or 'usuario') table in Supabase
 * Validating email and senha_hash.
 */
export async function authenticateWithUsuarioTable(
  emailInput: string,
  passwordInput: string
): Promise<{ user: TeamUser; role: UserRole }> {
  if (!supabase) {
    throw new Error(
      'O cliente Supabase não está configurado. Configure as variáveis VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY no arquivo .env.'
    );
  }

  const cleanEmail = emailInput.trim().toLowerCase();

  // Try querying 'usuarios' first (the new schema), fallback to 'usuario'
  let data: Record<string, unknown>[] | null = null;
  let queryError: unknown = null;

  const resUsuarios = await supabase
    .from('usuarios')
    .select('*')
    .ilike('email', cleanEmail)
    .limit(1);

  if (!resUsuarios.error && resUsuarios.data) {
    data = resUsuarios.data as Record<string, unknown>[];
  } else {
    // Try fallback to 'usuario' if 'usuarios' returned an error (e.g. table not found 42P01)
    const resUsuario = await supabase
      .from('usuario')
      .select('*')
      .ilike('email', cleanEmail)
      .limit(1);

    if (!resUsuario.error && resUsuario.data) {
      data = resUsuario.data as Record<string, unknown>[];
    } else {
      queryError = resUsuarios.error || resUsuario.error;
    }
  }

  if (queryError && (!data || data.length === 0)) {
    console.error('Erro ao consultar tabela de usuários no Supabase:', queryError);
    const errObj = queryError as { code?: string; message?: string };
    
    if (errObj.code === '42P01') {
      throw new Error(
        'A tabela "usuarios" (ou "usuario") não foi encontrada no banco Supabase. Certifique-se de criá-la no schema public.'
      );
    }
    
    if (errObj.message?.includes('row-level security') || errObj.code === '42501') {
      throw new Error(
        'Acesso bloqueado por RLS na tabela "usuarios". Habilite política de SELECT para a role anon.'
      );
    }

    throw new Error(`Erro ao consultar tabela de usuários: ${errObj.message || 'Falha de conexão'}`);
  }

  if (!data || data.length === 0) {
    throw new Error('Nenhum usuário encontrado com este e-mail na tabela "usuarios".');
  }

  const usuarioRow = data[0];

  // Check account status if column exists (ind_cadastro_ativo, ativo, etc.)
  if (
    usuarioRow.ind_cadastro_ativo === false ||
    usuarioRow.ativo === false ||
    usuarioRow.status === 'inativo' ||
    usuarioRow.bloqueado === true
  ) {
    throw new Error('Este usuário está inativo ou suspenso no sistema.');
  }

  // Validate senha_hash column
  const storedHash = (usuarioRow.senha_hash as string) || (usuarioRow.senha as string);

  if (!storedHash) {
    throw new Error('A coluna "senha_hash" não foi encontrada ou está vazia para este usuário.');
  }

  const isPasswordValid = await verifyPasswordHash(passwordInput, storedHash);

  if (!isPasswordValid) {
    throw new Error('Senha incorreta. Verifique suas credenciais de acesso.');
  }

  // Update ultimo_acesso_em if possible (fire & forget)
  try {
    const tableName = (usuarioRow.ind_cadastro_ativo !== undefined) ? 'usuarios' : 'usuario';
    await supabase
      .from(tableName)
      .update({ ultimo_acesso_em: new Date().toISOString() })
      .eq('id', usuarioRow.id);
  } catch {
    // Ignore update failures
  }

  const teamUser = mapUsuarioRowToTeamUser(usuarioRow);
  return { user: teamUser, role: teamUser.role };
}

/**
 * Registers a new user directly into the 'usuarios' table in Supabase
 */
export async function cadastrarUsuarioNaTabela(
  payload: NewUsuarioPayload
): Promise<TeamUser> {
  const cleanEmail = payload.email.trim().toLowerCase();
  const cleanNome = payload.nome.trim();

  // Generate initials for avatar
  const avatarIniciais =
    cleanNome
      .split(' ')
      .filter(Boolean)
      .slice(0, 2)
      .map(part => part[0]?.toUpperCase() || '')
      .join('') || cleanEmail.substring(0, 2).toUpperCase();

  // Hash the plain password using standard Bcrypt
  const senhaHash = generateBcryptHash(payload.senha);

  const newRecord: UsuarioDbRecord = {
    nome: cleanNome,
    email: cleanEmail,
    senha_hash: senhaHash,
    papel: payload.papel,
    departamento: payload.departamento.trim() || 'Engenharia de Dados & Governança',
    avatar_iniciais: avatarIniciais,
    mfa_habilitado: Boolean(payload.mfa_habilitado),
    pode_visualizar_pii_bruto: Boolean(payload.pode_visualizar_pii_bruto),
    ind_cadastro_ativo: true,
    id_empresa: payload.id_empresa || null,
  };

  if (isSupabaseConfigured() && supabase) {
    // Attempt inserting into 'usuarios'
    let insertResult = await supabase
      .from('usuarios')
      .insert([newRecord])
      .select()
      .single();

    if (insertResult.error) {
      // If table 'usuarios' doesn't exist, try fallback 'usuario'
      if (insertResult.error.code === '42P01') {
        const fallbackRecord = {
          nome: newRecord.nome,
          email: newRecord.email,
          senha_hash: newRecord.senha_hash,
          perfil: newRecord.papel,
          departamento: newRecord.departamento,
          ativo: true,
        };
        const fbResult = await supabase
          .from('usuario')
          .insert([fallbackRecord])
          .select()
          .single();

        if (fbResult.error) {
          throw new Error(`Erro ao cadastrar na tabela de usuários: ${fbResult.error.message}`);
        }
        insertResult = fbResult;
      } else if (insertResult.error.code === '23505') {
        throw new Error(`Já existe um usuário cadastrado com o e-mail "${cleanEmail}".`);
      } else {
        throw new Error(`Erro ao salvar usuário no Supabase: ${insertResult.error.message}`);
      }
    }

    return mapUsuarioRowToTeamUser(insertResult.data as Record<string, unknown>);
  } else {
    // Local demo simulation
    const localUser: TeamUser = {
      id: `usr-${Date.now()}`,
      name: cleanNome,
      email: cleanEmail,
      role: payload.papel,
      department: payload.departamento || 'Engenharia de Dados & Governança',
      avatar: avatarIniciais,
      lastActive: 'Agora',
      mfaEnabled: Boolean(payload.mfa_habilitado),
      canViewUnmaskedPII: Boolean(payload.pode_visualizar_pii_bruto),
    };
    return localUser;
  }
}

/**
 * Log out from Supabase and clear session
 */
export async function logoutFromSupabase(): Promise<void> {
  if (supabase) {
    try {
      await supabase.auth.signOut();
    } catch {
      // ignore
    }
  }
}

// =============================================================================
// Empresas (tenants) — ver sql/001_multi_tenant_empresas.sql
// =============================================================================

function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '') || `empresa-${Date.now()}`;
}

function mapEmpresaRow(row: Record<string, unknown>): Empresa {
  return {
    id: Number(row.id),
    nome: String(row.nome || ''),
    slug: String(row.slug || ''),
    airbyteWorkspaceId: (row.airbyte_workspace_id as string) || null,
    status: (row.status as Empresa['status']) || 'ativo',
    plano: (row.plano as string) || null,
    criadoEm: row.criado_em ? String(row.criado_em) : '',
  };
}

export async function fetchEmpresas(): Promise<Empresa[]> {
  if (!supabase) throw new Error('Supabase não configurado.');
  const { data, error } = await supabase.from('empresas').select('*').order('nome', { ascending: true });
  if (error) throw new Error(`Erro ao buscar empresas: ${error.message}`);
  return (data || []).map(mapEmpresaRow);
}

export async function createEmpresa(payload: {
  nome: string;
  plano?: string | null;
  airbyteWorkspaceId?: string | null;
}): Promise<Empresa> {
  if (!supabase) throw new Error('Supabase não configurado.');
  const nome = payload.nome.trim();
  const slug = slugify(nome);

  const { data, error } = await supabase
    .from('empresas')
    .insert([{
      nome,
      slug,
      plano: payload.plano?.trim() || null,
      airbyte_workspace_id: payload.airbyteWorkspaceId?.trim() || null,
    }])
    .select()
    .single();

  if (error) {
    if (error.code === '23505') {
      throw new Error(`Já existe uma empresa com identificador (slug) "${slug}". Escolha um nome diferente.`);
    }
    throw new Error(`Erro ao criar empresa: ${error.message}`);
  }

  return mapEmpresaRow(data);
}

export async function updateEmpresaStatus(id: number, status: Empresa['status']): Promise<void> {
  if (!supabase) throw new Error('Supabase não configurado.');
  const { error } = await supabase
    .from('empresas')
    .update({ status, atualizado_em: new Date().toISOString() })
    .eq('id', id);
  if (error) throw new Error(`Erro ao atualizar status da empresa: ${error.message}`);
}

export async function vincularUsuarioAEmpresa(usuarioId: string, idEmpresa: number | null): Promise<void> {
  if (!supabase) throw new Error('Supabase não configurado.');
  const { error } = await supabase.from('usuarios').update({ id_empresa: idEmpresa }).eq('id', usuarioId);
  if (error) throw new Error(`Erro ao vincular usuário à empresa: ${error.message}`);
}

// =============================================================================
// Origens / Destinos / Integrações — persistência por empresa do que hoje só
// existe como estado React no wizard de Pipeline Automático.
// =============================================================================

function mapOrigemRowToSourceConfig(row: Record<string, unknown>): SourceConnectorConfig {
  const cfg = (row.configuracao as Record<string, unknown>) || {};
  return {
    id: String(row.airbyte_source_id),
    name: String(row.nome || ''),
    type: (row.tipo as SourceType) || 'postgres',
    provider: (cfg.provider as CloudProvider) || 'generic',
    host: (cfg.host as string) || '-',
    port: (cfg.port as number) ?? 0,
    database: (cfg.database as string) || '-',
    username: (cfg.username as string) || '',
    schema: cfg.schema as string | undefined,
    ssl: Boolean(cfg.ssl),
    discoveredTables: [],
    status: (row.status as SourceConnectorConfig['status']) || 'connected',
    lastTestedAt: 'Sincronizado do banco',
    createdAt: row.criado_em ? String(row.criado_em).split('T')[0] : '',
  };
}

export async function fetchOrigensPorEmpresa(idEmpresa: number): Promise<SourceConnectorConfig[]> {
  if (!supabase) return [];
  const { data, error } = await supabase
    .from('origens')
    .select('*')
    .eq('id_empresa', idEmpresa)
    .order('criado_em', { ascending: false });
  if (error) throw new Error(`Erro ao buscar origens da empresa: ${error.message}`);
  return (data || []).map(mapOrigemRowToSourceConfig);
}

/** Upserts a real Airbyte source into the tenant-scoped registry. Returns the row's own bigint id. */
export async function registrarOrigem(idEmpresa: number, source: SourceConnectorConfig): Promise<number> {
  if (!supabase) throw new Error('Supabase não configurado.');
  const { data, error } = await supabase
    .from('origens')
    .upsert(
      {
        id_empresa: idEmpresa,
        airbyte_source_id: source.id,
        nome: source.name,
        tipo: source.type,
        configuracao: {
          provider: source.provider,
          host: source.host,
          port: source.port,
          database: source.database,
          username: source.username,
          schema: source.schema,
          ssl: source.ssl,
        },
        status: source.status,
      },
      { onConflict: 'id_empresa,airbyte_source_id' }
    )
    .select('id')
    .single();

  if (error) throw new Error(`Erro ao registrar origem no banco: ${error.message}`);
  return Number(data.id);
}

function mapDestinoRowToDestConfig(row: Record<string, unknown>): DestinationConnectorConfig {
  const cfg = (row.configuracao as Record<string, unknown>) || {};
  return {
    id: String(row.airbyte_destination_id),
    name: String(row.nome || ''),
    type: (row.tipo as DestinationType) || 'bigquery',
    provider: (cfg.provider as CloudProvider) || 'generic',
    accountOrProject: (cfg.accountOrProject as string) || '-',
    warehouseOrCluster: cfg.warehouseOrCluster as string | undefined,
    databaseOrDataset: (cfg.databaseOrDataset as string) || '-',
    schema: cfg.schema as string | undefined,
    authMethod: (cfg.authMethod as DestinationConnectorConfig['authMethod']) || 'service_account',
    writeMode: (row.modo_escrita as DestinationConnectorConfig['writeMode']) || 'merge_upsert',
    status: (row.status as DestinationConnectorConfig['status']) || 'connected',
    lastTestedAt: 'Sincronizado do banco',
    createdAt: row.criado_em ? String(row.criado_em).split('T')[0] : '',
  };
}

export async function fetchDestinosPorEmpresa(idEmpresa: number): Promise<DestinationConnectorConfig[]> {
  if (!supabase) return [];
  const { data, error } = await supabase
    .from('destinos')
    .select('*')
    .eq('id_empresa', idEmpresa)
    .order('criado_em', { ascending: false });
  if (error) throw new Error(`Erro ao buscar destinos da empresa: ${error.message}`);
  return (data || []).map(mapDestinoRowToDestConfig);
}

/** Upserts a real Airbyte destination into the tenant-scoped registry. Returns the row's own bigint id. */
export async function registrarDestino(idEmpresa: number, dest: DestinationConnectorConfig): Promise<number> {
  if (!supabase) throw new Error('Supabase não configurado.');
  const { data, error } = await supabase
    .from('destinos')
    .upsert(
      {
        id_empresa: idEmpresa,
        airbyte_destination_id: dest.id,
        nome: dest.name,
        tipo: dest.type,
        configuracao: {
          provider: dest.provider,
          accountOrProject: dest.accountOrProject,
          warehouseOrCluster: dest.warehouseOrCluster,
          databaseOrDataset: dest.databaseOrDataset,
          schema: dest.schema,
          authMethod: dest.authMethod,
        },
        modo_escrita: dest.writeMode,
        status: dest.status,
      },
      { onConflict: 'id_empresa,airbyte_destination_id' }
    )
    .select('id')
    .single();

  if (error) throw new Error(`Erro ao registrar destino no banco: ${error.message}`);
  return Number(data.id);
}

function mapIntegracaoRow(row: Record<string, unknown>): AutoIntegration {
  const origem = (row.origens as Record<string, unknown>) || {};
  const destino = (row.destinos as Record<string, unknown>) || {};
  const selectedTables = (row.tabelas_selecionadas as string[]) || [];

  return {
    id: String(row.id),
    name: String(row.nome || ''),
    sourceConnectorId: String(origem.airbyte_source_id || ''),
    sourceConnectorName: String(origem.nome || ''),
    sourceType: (origem.tipo as SourceType) || 'postgres',
    destinationConnectorId: String(destino.airbyte_destination_id || ''),
    destinationConnectorName: String(destino.nome || ''),
    destinationType: (destino.tipo as DestinationType) || 'bigquery',
    selectedTables,
    tableSyncConfigs: (row.table_sync_configs as Record<string, TableSyncConfig>) || {},
    syncFrequency: (row.frequencia_sync as SyncFrequencyOption) || 'daily',
    executionTimes: (row.horarios_execucao as string[]) || [],
    weeklyDays: (row.dias_semana as string[] | null) || undefined,
    monthlyDay: row.dia_mensal !== null && row.dia_mensal !== undefined ? Number(row.dia_mensal) : undefined,
    onceDate: (row.data_execucao_unica as string) || undefined,
    scheduleSummary: (row.resumo_agendamento as string) || undefined,
    applyLgpdSanitization: Boolean(row.aplicar_sanitizacao_lgpd),
    airbyteConnectionId: (row.airbyte_connection_id as string) || undefined,
    status: (row.status as AutoIntegration['status']) || 'active',
    pipelineId: String(row.pipeline_id || ''),
    createdAt: row.criado_em ? String(row.criado_em).split('T')[0] : '',
    tablesCount: selectedTables.length,
  };
}

export async function fetchIntegracoesPorEmpresa(idEmpresa: number): Promise<AutoIntegration[]> {
  if (!supabase) return [];
  const { data, error } = await supabase
    .from('integracoes')
    .select('*, origens(nome, tipo, airbyte_source_id), destinos(nome, tipo, airbyte_destination_id)')
    .eq('id_empresa', idEmpresa)
    .order('criado_em', { ascending: false });
  if (error) throw new Error(`Erro ao buscar integrações da empresa: ${error.message}`);
  return (data || []).map(mapIntegracaoRow);
}

/** Persists an AutoIntegration record. origemDbId/destinoDbId are the bigint ids from registrarOrigem/registrarDestino (not the Airbyte UUIDs). */
export async function registrarIntegracao(
  idEmpresa: number,
  integration: AutoIntegration,
  origemDbId: number,
  destinoDbId: number
): Promise<void> {
  if (!supabase) throw new Error('Supabase não configurado.');
  const { error } = await supabase.from('integracoes').insert([{
    id_empresa: idEmpresa,
    origem_id: origemDbId,
    destino_id: destinoDbId,
    airbyte_connection_id: integration.airbyteConnectionId || null,
    nome: integration.name,
    tabelas_selecionadas: integration.selectedTables,
    table_sync_configs: integration.tableSyncConfigs || {},
    frequencia_sync: integration.syncFrequency,
    horarios_execucao: integration.executionTimes || [],
    dias_semana: integration.weeklyDays || null,
    dia_mensal: integration.monthlyDay ?? null,
    data_execucao_unica: integration.onceDate || null,
    resumo_agendamento: integration.scheduleSummary || null,
    aplicar_sanitizacao_lgpd: integration.applyLgpdSanitization,
    status: integration.status,
    pipeline_id: integration.pipelineId,
  }]);
  if (error) throw new Error(`Erro ao registrar integração no banco: ${error.message}`);
}
